### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by ShalokShalom**
;)

### CODE REVIEW

**Comment by evancz** [comment]
You seem to be parsing it as uses/gives. I wrote it where it uses type inference to detect/give things.

Both are valid ways to parse the sentence.

**Comment by harrysarson** [comment]
The sentance in question currently reads:

>  Instead, Elm uses type inference to detect problems during **compilation and give friendly** hints.

If my grammar isn't letting me down then either

> compilation and gives friendly

or

> compilation to give friendly

are correct.

The first version is the change that @ShalokShalom wanted to make in this PR. The second version is equaly valid. The current text is neither though.

**Comment by harrysarson** [comment]
On second thoughts I think there are three valid ways of phrasing the sentance and the current version is okay.

**Comment by BrianHicks** [comment]
Harry, thanks for your feedback. We're going to leave it as is for now.

**Pull request closed without merging**
