### PR TITLE
Add Culture Amp featured user quote to home page

### PR DESCRIPTION
**Pull request by sentience**
This required a CSS change to allow two blocks with stylized quotation marks on the page at once. Without this change, the browser displayed the second as a single quote instead of a double quote.

culture_amp_quote

### CODE REVIEW

**Comment by evancz** [comment]
My current plan is to have any company that gets added to have a link to a blog post about how they are using it at work. I will pick out quotations from there.

It seems like you are suggesting a more "endorsement" style for this section. I can talk with some folks to see if that is an alright direction for this section. I'm not immediately sure one way or the other.

**Comment by sentience** [comment]
I said something very similar to my quote while recording the latest episode of Elm Town, and I had wanted to just link to that, but when I went back to listen to the edited episode, my remark didn't make the cut in editing. I was hoping the tweet might be an acceptable substitute.

I'm happy to write up something a little more long-form for you to pick and choose from, but Culture Amp doesn't have a tech blog, so I'd need to post it on my somewhat neglected [personal blog](https://www.kevinyank.com/) instead. I'm not sure what you'd put for the link text in that case (“Personal Blog”?).

Alternatively, we could dispense with the quote and I could just add Culture Amp to the logos at the bottom. I'd certainly like to be able to contribute some words of support, but if you prefer just the logo let me know and I can update.

**Comment by evancz** [comment]
I talked with some other folks, and I think we want to keep the requirement about having a blog post about how people use Elm at the company. How did you get started? What have the benefits been? Have their been a reduction in bugs? Ideally quantifiable stuff.

We actually used to have a bunch more logos on the page, but I filtered it down to the specific companies that have something like that.

I understand that it's not everyone's preference, but I think it will work out better overall for Elm this way.

**Comment by sentience** [comment]
Sure thing! Would me posting about Culture Amp's experience on my personal blog be okay, or would you need the post to be on a company-branded page? As I mentioned above, Culture Amp doesn't currently have a tech blog.

**Pull request closed without merging**
